/** Report rendering: one dataset → PDF / XLSX / CSV. */
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export type Cell = string | number | null;
export interface ReportSection { heading: string; columns: string[]; rows: Cell[][]; note?: string }
export interface ReportDataset {
  title: string;
  subtitle?: string;
  meta: [string, string][];
  sections: ReportSection[];
  generatedBy: string;
  generatedAt: string;
}
export type ReportFormat = "PDF" | "XLSX" | "CSV";

const csvEscape = (v: Cell) => {
  const s = v === null || v === undefined ? "" : String(v);
  // neutralise spreadsheet formula injection
  const safe = /^[=+\-@\t\r]/.test(s) && !/^-?\d+(\.\d+)?$/.test(s) ? `'${s}` : s;
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
};

export function renderCsv(d: ReportDataset): Buffer {
  const lines: string[] = [csvEscape(d.title)];
  for (const [k, v] of d.meta) lines.push(`${csvEscape(k)},${csvEscape(v)}`);
  for (const s of d.sections) {
    lines.push("", csvEscape(s.heading), s.columns.map(csvEscape).join(","));
    for (const r of s.rows) lines.push(r.map(csvEscape).join(","));
    if (s.note) lines.push(csvEscape(s.note));
  }
  lines.push("", `${csvEscape("Generated by")},${csvEscape(d.generatedBy)}`, `${csvEscape("Generated at")},${csvEscape(d.generatedAt)}`);
  return Buffer.from("﻿" + lines.join("\r\n"), "utf8");
}

export function renderXlsx(d: ReportDataset): Buffer {
  const wb = XLSX.utils.book_new();
  const summary: Cell[][] = [[d.title], ...(d.subtitle ? [[d.subtitle]] : []), [], ...d.meta.map(([k, v]) => [k, v]), [], ["Generated by", d.generatedBy], ["Generated at", d.generatedAt]];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summary), "Summary");
  const used = new Set<string>(["Summary"]);
  for (const s of d.sections) {
    let name = s.heading.replace(/[\\/?*[\]:]/g, " ").slice(0, 28).trim() || "Sheet";
    let i = 2;
    while (used.has(name)) name = `${name.slice(0, 25)} ${i++}`;
    used.add(name);
    const aoa: Cell[][] = [[s.heading], s.columns, ...s.rows];
    if (s.note) aoa.push([], [s.note]);
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws["!cols"] = s.columns.map((c, idx) => ({ wch: Math.min(60, Math.max(c.length, ...s.rows.map((r) => String(r[idx] ?? "").length)) + 2) }));
    XLSX.utils.book_append_sheet(wb, ws, name);
  }
  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

/** Standard PDF fonts are WinAnsi-encoded; map symbols used in formulas. */
export function pdfSafe(v: string) {
  return v
    .replace(/≥/g, ">=").replace(/≤/g, "<=").replace(/Σ/g, "Sum ").replace(/[−–]/g, "-").replace(/…/g, "...")
    .replace(/[^\x00-\xFF—•×÷·]/g, "?");
}

export function renderPdf(input: ReportDataset): Buffer {
  const d: ReportDataset = {
    ...input,
    title: pdfSafe(input.title),
    subtitle: input.subtitle ? pdfSafe(input.subtitle) : undefined,
    meta: input.meta.map(([k, v]) => [pdfSafe(k), pdfSafe(v)]),
    sections: input.sections.map((s) => ({
      heading: pdfSafe(s.heading),
      columns: s.columns.map(pdfSafe),
      rows: s.rows.map((r) => r.map((c) => (typeof c === "string" ? pdfSafe(c) : c))),
      note: s.note ? pdfSafe(s.note) : undefined,
    })),
  };
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageW, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(30, 27, 75);
  doc.text(d.title, 40, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 110);
  if (d.subtitle) doc.text(d.subtitle, 40, 56);
  let y = d.subtitle ? 74 : 60;
  const metaCols = 3;
  d.meta.forEach(([k, v], i) => {
    const x = 40 + (i % metaCols) * ((pageW - 80) / metaCols);
    if (i > 0 && i % metaCols === 0) y += 14;
    doc.setFont("helvetica", "bold");
    doc.text(`${k}: `, x, y);
    doc.setFont("helvetica", "normal");
    doc.text(String(v).slice(0, 60), x + doc.getTextWidth(`${k}: `), y);
  });
  y += 20;
  const pageH = doc.internal.pageSize.getHeight();
  for (const s of d.sections) {
    if (y > pageH - 90) {
      doc.addPage();
      y = 50;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(76, 29, 149);
    doc.text(s.heading, 40, y);
    autoTable(doc, {
      startY: y + 8,
      head: [s.columns],
      body: s.rows.map((r) => r.map((c) => (c === null || c === undefined ? "—" : String(c)))),
      margin: { left: 40, right: 40, bottom: 40 },
      styles: { fontSize: 8, cellPadding: 3, overflow: "linebreak" },
      headStyles: { fillColor: [237, 233, 254], textColor: [49, 46, 129], fontStyle: "bold" },
      alternateRowStyles: { fillColor: [250, 249, 255] },
      tableLineColor: [221, 214, 254],
      tableLineWidth: 0.5,
    });
    const last = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable;
    y = (last?.finalY ?? y) + 14;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(90, 90, 110);
    if (s.note) {
      const lines = doc.splitTextToSize(s.note, pageW - 80) as string[];
      doc.setFontSize(8);
      if (y + lines.length * 10 > pageH - 40) {
        doc.addPage();
        y = 50;
      }
      doc.text(lines, 40, y);
      y += lines.length * 10 + 6;
    }
    doc.setFontSize(10);
    y += 16;
  }
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 160);
    doc.text(`OBE IQAC Command Center · Generated by ${d.generatedBy} · ${d.generatedAt} · Page ${i}/${pages}`, 40, doc.internal.pageSize.getHeight() - 20);
  }
  return Buffer.from(doc.output("arraybuffer"));
}

export function render(d: ReportDataset, format: ReportFormat) {
  if (format === "CSV") return { data: renderCsv(d), contentType: "text/csv; charset=utf-8", ext: "csv" };
  if (format === "XLSX") return { data: renderXlsx(d), contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ext: "xlsx" };
  return { data: renderPdf(d), contentType: "application/pdf", ext: "pdf" };
}
