/** NBA/Washington Accord graduate attributes used to initialise engineering programs. */
export const STANDARD_ENGINEERING_POS: { code: string; title: string; description: string }[] = [
  { code: "PO1", title: "Engineering knowledge", description: "Apply the knowledge of mathematics, science, engineering fundamentals, and an engineering specialization to the solution of complex engineering problems." },
  { code: "PO2", title: "Problem analysis", description: "Identify, formulate, review research literature, and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences, and engineering sciences." },
  { code: "PO3", title: "Design/development of solutions", description: "Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for public health and safety, and cultural, societal, and environmental considerations." },
  { code: "PO4", title: "Conduct investigations of complex problems", description: "Use research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions." },
  { code: "PO5", title: "Modern tool usage", description: "Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modeling to complex engineering activities with an understanding of the limitations." },
  { code: "PO6", title: "The engineer and society", description: "Apply reasoning informed by contextual knowledge to assess societal, health, safety, legal and cultural issues and the consequent responsibilities relevant to professional engineering practice." },
  { code: "PO7", title: "Environment and sustainability", description: "Understand the impact of professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for, sustainable development." },
  { code: "PO8", title: "Ethics", description: "Apply ethical principles and commit to professional ethics and responsibilities and norms of engineering practice." },
  { code: "PO9", title: "Individual and team work", description: "Function effectively as an individual, and as a member or leader in diverse teams, and in multidisciplinary settings." },
  { code: "PO10", title: "Communication", description: "Communicate effectively on complex engineering activities with the engineering community and with society at large, such as writing effective reports and design documentation, making effective presentations, and giving and receiving clear instructions." },
  { code: "PO11", title: "Project management and finance", description: "Demonstrate knowledge and understanding of engineering and management principles and apply these to one's own work, as a member and leader in a team, to manage projects in multidisciplinary environments." },
  { code: "PO12", title: "Life-long learning", description: "Recognize the need for, and have the preparation and ability to engage in, independent and life-long learning in the broadest context of technological change." },
];
